using System.Threading;



var chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
var stringChars = new char[16];
var random = new Random();
Console.ForegroundColor = ConsoleColor.Blue;
string text = @"
  _    _ _   _______ _____ __  __       _______ ______    _____ ______ _   _ ______ _____        _______ ____  _____  
 | |  | | | |__   __|_   _|  \/  |   /\|__   __|  ____|  / ____|  ____| \ | |  ____|  __ \    /\|__   __/ __ \|  __ \ 
 | |  | | |    | |    | | | \  / |  /  \  | |  | |__    | |  __| |__  |  \| | |__  | |__) |  /  \  | | | |  | | |__) |
 | |  | | |    | |    | | | |\/| | / /\ \ | |  |  __|   | | |_ |  __| | . ` |  __| |  _  /  / /\ \ | | | |  | |  _  / 
 | |__| | |____| |   _| |_| |  | |/ ____ \| |  | |____  | |__| | |____| |\  | |____| | \ \ / ____ \| | | |__| | | \ \ 
  \____/|______|_|  |_____|_|  |_/_/    \_|_|  |______|  \_____|______|_| \_|______|_|  \_/_/    \_|_|  \____/|_|  \_\
                                                                                                                      
                                                                                                                      
";
Console.WriteLine(text);
Thread.Sleep(2000);
Console.Clear();
Console.WriteLine(text);
Console.WriteLine("What do you want generate? ");
Console.WriteLine("[1] Discord Nitro");
Console.WriteLine("[2] PaySafeCard Code");
Console.WriteLine("[3] Steam Gift Codes");
Console.Write(">");
var wybor = Convert.ToInt32(Console.ReadLine());
Console.Clear();
    if (wybor == 1)
    {
        Console.WriteLine(text);
        Console.WriteLine("HOW MANY DISCORD NITRO CODES DO YOU WANT GENERATE?: ");
        Console.Write(">");
        var dlugosc = Convert.ToInt32(Console.ReadLine());
        Console.Clear();
        Console.WriteLine(text);
        Console.WriteLine("Generating...");
        using (StreamWriter writer = new StreamWriter("nitrocodes.txt", true))
        {
            writer.WriteLine("########## NITRO CODES GENERATED BY ULTIMATEGENERATOR ##########");
            writer.WriteLine("########## IF YOU WANT CHECK IT MANUALLY WRITE DISCORD.GIFT/ BEFORE THE CODE ##########");
        }
        for (int j = 0; j < dlugosc; j++)
        {
            for (int i = 0; i < stringChars.Length; i++)
            {
                stringChars[i] = chars[random.Next(chars.Length)];
            }
            var finalString = new String(stringChars);
            Console.WriteLine("discord.gift/" + finalString);
            using (StreamWriter writer = new StreamWriter("nitrocodes.txt", true))
            {
                writer.WriteLine(finalString);
            }
        }
        Console.WriteLine("Nitro codes are saved in nitrocodes.txt");
        Console.WriteLine("YOUR CODES ARE READY TO CHECK!");
        Console.ReadKey();
    }
    if (wybor == 2)
    {

        var numbers = "0123456789";
        var intNumbers = new char[16];
        var randomnumbers = new Random();
        Console.WriteLine(text);
        Console.WriteLine("HOW MANY PAYSAFECARD CODES DO YOU WANT GENERATE?: ");
        Console.Write(">");
        var dlugosc = Convert.ToInt32(Console.ReadLine());
        Console.Clear();
        Console.WriteLine("Generating...");
        using (StreamWriter writer = new StreamWriter("codespsc.txt", true))
        {
            writer.WriteLine("########## PAYSAFECARD CODES GENERATED BY ULTIMATEGENERATOR ##########");
        }
        for (int j = 0; j < dlugosc; j++)
        {
            for (int i = 0; i < intNumbers.Length; i++)
            {
                intNumbers[i] = numbers[random.Next(numbers.Length)];
            }
            var finalNumbers = new String(intNumbers);
            Console.WriteLine(finalNumbers);
            using (StreamWriter writer = new StreamWriter("codespsc.txt", true))
            {
                writer.WriteLine(finalNumbers);
            }
        }
        Console.WriteLine("PAYSAFECARD CODES ARE SAVED IN codespsc.txt");
        Console.ReadKey();
    }
    if (wybor == 3)
    {

        var steamchars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        var stringSteam = new char[15];
        var randomsteam = new Random();
        Console.WriteLine(text);
        Console.WriteLine("HOW MANY STEAM GIFT CODES DO YOU WANT GENERATE?: ");
        Console.Write(">");
        var dlugosc = Convert.ToInt32(Console.ReadLine());
        Console.Clear();
        Console.WriteLine("Generating...");
        using (StreamWriter writer = new StreamWriter("steamcodes.txt", true))
        {
            writer.WriteLine("########## STEAM GIFT CODES GENERATED BY ULTIMATEGENERATOR ##########");
        }
        for (int j = 0; j < dlugosc; j++)
        {
            for (int i = 0; i < stringSteam.Length; i++)
            {
                stringSteam[i] = steamchars[random.Next(steamchars.Length)];
            }
            var finalSteam = new String(stringSteam);
            Console.WriteLine(finalSteam);
            using (StreamWriter writer = new StreamWriter("steamcodes.txt", true))
            {
                writer.WriteLine(finalSteam);
            }
        }
        Console.WriteLine("STEAM GIFT CODES ARE SAVED IN steamcodes.txt");
        Console.ReadKey();
    }



